# Generated by Django 5.1.3 on 2025-05-19 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustlehub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='added_jobs',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='applied_jobs',
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('post_date', models.DateField(auto_now_add=True, verbose_name='posted')),
                ('salary', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('experience', models.IntegerField()),
                ('logo', models.ImageField(upload_to='static/assets/')),
                ('details_link', models.CharField(blank=True, max_length=255, null=True)),
                ('added_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='added', to=settings.AUTH_USER_MODEL)),
                ('applied', models.ManyToManyField(blank=True, related_name='applied_to', to=settings.AUTH_USER_MODEL)),
                ('career_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_in_level', to='hustlehub.career_level')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_in_category', to='hustlehub.categories')),
                ('countries', models.ManyToManyField(related_name='countries', to='hustlehub.countries')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_in_jobType', to='hustlehub.jobtype')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_in_workplace', to='hustlehub.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tags', to='hustlehub.jobs')),
            ],
        ),
    ]
