# Generated by Django 5.1.3 on 2025-05-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustlehub', '0002_career_level_categories_countries_jobtype_workplace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='description',
            field=models.TextField(default='No description yet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='countries',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='countries', to='hustlehub.countries'),
        ),
    ]
