# Generated by Django 5.2.1 on 2025-05-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustlehub', '0005_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='applied_jobs',
            field=models.ManyToManyField(blank=True, related_name='applied_users', to='hustlehub.jobs'),
        ),
    ]
